version: '3.7'

services:

  sqlnodeplate:
    image: sqlnodeplate
    restart: unless-stopped
    container_name: sqlnodeplate
    build: ./node/
    ports:
      - 3001:3001
    networks:
      - my-net
      
  mysql:
    image: mysql
    restart: unless-stopped
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    build: ./database/
    ports:
      - 3306:3306
    networks:
      - my-net
      
networks: 
  my-net: